[tox]
requires =
    tox==4.30.2
    tox-uv==1.28.0
env_list = e2e-platform

[testenv:e2e-platform]
description = Validate platform components are healthy (post-deploy)
deps = -r tests/e2e/platform/requirements.txt
passenv =
    KUBECONFIG
changedir = tests
commands =
    pytest -vv -s --capture=tee-sys --alluredir allure-results --clean-alluredir e2e/platform {posargs}

